version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./GeoLite2-Country.mmdb:/app/GeoLite2-Country.mmdb
    expose:
      - "5003"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  nginx:
    image: nginx:latest
    ports:
      - "5003:5003"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  redis-data:
