version: '3.8'

services:
  web:                                                   # web service 
    build: .
    expose:                                              # Expose allows port:5002 to be available to other services within docker network
    - "5002"                                             # Expose doesnt bind like "ports:" 
    depends_on: 
      - redis
    environment:                                         # Passes count.py environment variables to flask service
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:                                             # Volume allows redis to remember.
    - redis-data:/data                                   # Mount redis data volume to "/data" in redis container

  nginx:                                                 # Bind to reverse proxy for "Expose"
    image: nginx:latest
    ports:
     - "5002:5002"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf               # Mounting a custom config file, ngnix container to configure load balancing
    depends_on:
     - web

volumes:                                                 # Volume allows redis to remember.
  redis-data:                                            # Redis will store actual data volume in a persistent location on the host

